server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/k6leung/CodingChallengeAppConfig.git
          clone-on-start: true
          search-paths:
          - CodingChallengeAppConfig/CodingChallengeAppAuthenticationService
          - CodingChallengeAppConfig/CodingChallengeIntegrationBus
          - CodingChallengeAppConfig/CodingChallengeOAuth2AuthorizationServer
          - CodingChallengeAppConfig/CodingChallengeReportService
          - CodingChallengeAppConfig/CodingChallengeWebTomcatServer
          
          
security:
  basic:
    enabled: true
---    
spring:
  profiles: dev
security:    
  user:
    name: ken
    password: ken
---
spring:
  profiles: sit
security:    
  user:
    name: ken
    password: ken  
server:
  ssl:
    enabled: true
    key-store: ./keystore/keystore.jks
    key-store-password: abc1234
    key-alias: localhostTest
    key-password: abc1234
    keyStoreType: PKCS12